apiVersion: v2
name: dcraft-fusion
description: DCraft Fusion control plane (kernel API and web UI). Bring your own Postgres and Redis.
type: application
version: 1.2.22
appVersion: "1.2.22"
keywords:
  - dcraft
  - fusion
  - control-plane
home: https://github.com/DCraft-Labs/dcraft-fusion
sources:
  - https://github.com/DCraft-Labs/dcraft-fusion
maintainers:
  - name: DCraft Labs
    email: platform@dcraftlabs.com
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/prerelease: "false"
