apiVersion: v1
kind: ConfigMap
metadata:
  name: fusion-secret-provider-map
  namespace: dcraft-fusion
data:
  vault: vault://kv/dcraft-fusion
  aws: arn:aws:secretsmanager:*:*:secret:dcraft-fusion/*
  gcp: projects/*/secrets/dcraft-fusion-*
  azure: https://*.vault.azure.net/secrets/dcraft-fusion-*
