apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - control-plane-kernel.yaml
  - web.yaml
  - ha.yaml
  - backup-cronjob.yaml
  - external-secrets.yaml
